server:
  port: 8082

spring:
  application:
    name: order-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  threads:
    virtual:
      enabled: true

  rabbitmq:
    listener:
      type: simple
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 1

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
      deferred-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}

  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.flywaydb: DEBUG

  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-},orderId=%X{orderId:-}]"

springdoc:
  api-docs:
    path: /v3/api-docs

