server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/orders
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  threads:
    virtual:
      enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: book_user
    password: book_password

flyway:
  enabled: true
  locations: classpath:db/migration

jpa:
  hibernate:
    ddl-auto: validate
    deferred-datasource-initialization: true

logging:
  level:
    org.springframework: DEBUG

#resilience4j:
#  retry:
#    instances:
#      paymentRetry:
#        max-attempts: 3
#        wait-duration: 2s
#
#  circuitbreaker:
#    instances:
#      paymentCircuit:
#        sliding-window-size: 5
#        failure-rate-threshold: 50
#
#  timelimiter:
#    instances:
#      paymentTimeout:
#        timeout-duration: 2s
